### ISSUE TITLE
Native Chunked Functionality

### ISSUE THREAD

**Issue by CMCDragonkai** [agentzh/chunkin-nginx-module#10]
Since NGINX now supports chunked HTTP requests natively: http://nginx.org/en/docs/http/ngx_http_core_module.html#chunked_transfer_encoding

Does this mean NGINX captures the request and batches up the chunks and sends a normal request to the upstream server?

Or is it possible for NGINX to simply proxy all the chunks to the upstream server? I didn't see any directives in native NGINX that supports these options?

**Comment by agentzh** [comment]
@CMCDragonkai Your question is really related to the nginx core instead of this module. For such general questions, please join the nginx or openresty-en mailing lists instead.

Regarding your question, yes, the recent nginx cores work in a similar fashion as this module, read and parse the chunked request body, stripping any chunked encoding stuff before forwarding it to other modules (including ngx_proxy).

**Comment by CMCDragonkai** [comment]
Thanks, so it buffers up all the chunks before pushing to the upstream? No option for just chunking pass through?

**Comment by agentzh** [comment]
@CMCDragonkai See http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_request_buffering
